services:
  posts-service:
    image: sushantpaudel77/my_linkedin-posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - posts-db

  user-service:
    image: sushantpaudel77/my_linkedin-user-service
    container_name: user-service
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - linkedin-network
    depends_on:
      - user-db

  posts-db:
    image: postgres
    container_name: posts-db
    environment:
      - POSTGRES_DB=postsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - linkedin-network
    volumes:
      - posts-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_DB=usersDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - linkedin-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

networks:
  linkedin-network:

volumes:
  posts-db-data:
  user-db-data:
